version: "3.7"
services:
  jupyter-medimproc:
    depends_on:
      - common-base-image
    build:
      context: .
      dockerfile: services/jupyter/Dockerfile
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "https://github.com/ITISFoundation/jupyter-medimproc"
        org.label-schema.vcs-ref: "${VCS_REF}"
        simcore.service.settings: '[{"name":"Resources","type":"Resources","value":{"Limits":{"NanoCPUs":4000000000,"MemoryBytes":17179869184}}}]'
