services:
  medimproc-common:
    image: medimproc-common:${VERSION}
    build:
      context: .
      dockerfile: common/Dockerfile.base
      network: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
