version: "3.7"
services:
  runner-medimproc-slim:
    depends_on:
      - medimproc-common
    build:
      context: .
      dockerfile: services/runner-slim/Dockerfile
      args:
        VERSION: "1.3.3"
